/** @type {import('tailwindcss').Config} */
// Every value here points at a CSS variable defined in src/index.css.
// Namespaces that are NOT under `extend` (colors, radius, shadows, type, etc.)
// intentionally replace Tailwind's defaults so stock values can't creep back in.
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      ink: {
        DEFAULT: 'var(--ink)',
        deep: 'var(--ink-deep)',
      },
      surface: {
        DEFAULT: 'var(--surface)',
        raised: 'var(--surface-raised)',
        hover: 'var(--surface-hover)',
      },
      line: {
        DEFAULT: 'var(--line)',
        strong: 'var(--line-strong)',
      },
      fg: {
        DEFAULT: 'var(--fg)',
        muted: 'var(--fg-muted)',
        subtle: 'var(--fg-subtle)',
      },
      accent: {
        DEFAULT: 'var(--accent)',
        strong: 'var(--accent-strong)',
        ink: 'var(--accent-ink)',
        wash: 'var(--accent-wash)',
      },
      brass: {
        DEFAULT: 'var(--brass)',
        'on-image': 'var(--brass-on-image)',
      },
      positive: 'var(--positive)',
      negative: 'var(--negative)',
      scrim: {
        DEFAULT: 'var(--scrim)',
        soft: 'var(--scrim-soft)',
        solid: 'var(--scrim-solid)',
      },
      'on-image': 'var(--on-image)',
      imdb: {
        DEFAULT: 'var(--imdb)',
        ink: 'var(--imdb-ink)',
      },
    },
    fontFamily: {
      display: 'var(--font-display)',
      sans: 'var(--font-sans)',
      mono: 'var(--font-mono)',
    },
    fontSize: {
      micro: ['var(--text-micro)', { lineHeight: 'var(--leading-tight)' }],
      caption: ['var(--text-caption)', { lineHeight: 'var(--leading-snug)' }],
      small: ['var(--text-small)', { lineHeight: 'var(--leading-snug)' }],
      body: ['var(--text-body)', { lineHeight: 'var(--leading-body)' }],
      lead: ['var(--text-lead)', { lineHeight: 'var(--leading-body)' }],
      title: ['var(--text-title)', { lineHeight: 'var(--leading-tight)' }],
      section: ['var(--text-section)', { lineHeight: 'var(--leading-display)' }],
      heading: ['var(--text-heading)', { lineHeight: 'var(--leading-display)' }],
      display: ['var(--text-display)', { lineHeight: 'var(--leading-display)' }],
      mega: ['var(--text-mega)', { lineHeight: 'var(--leading-mega)' }],
    },
    letterSpacing: {
      tightest: 'var(--tracking-tightest)',
      tight: 'var(--tracking-tight)',
      normal: '0',
      wide: 'var(--tracking-wide)',
      label: 'var(--tracking-label)',
    },
    lineHeight: {
      none: '1',
      tight: 'var(--leading-tight)',
      snug: 'var(--leading-snug)',
      body: 'var(--leading-body)',
    },
    borderRadius: {
      none: '0',
      xs: 'var(--radius-xs)',
      sm: 'var(--radius-sm)',
      DEFAULT: 'var(--radius-sm)',
      md: 'var(--radius-md)',
      full: '9999px',
    },
    opacity: {
      0: '0',
      disabled: 'var(--opacity-disabled)',
      muted: 'var(--opacity-muted)',
      100: '1',
    },
    boxShadow: {
      none: 'none',
      hard: 'var(--shadow-hard)',
      lift: 'var(--shadow-lift)',
    },
    zIndex: {
      0: '0',
      raised: 'var(--z-raised)',
      nav: 'var(--z-nav)',
      dropdown: 'var(--z-dropdown)',
      dock: 'var(--z-dock)',
      modal: 'var(--z-modal)',
      toast: 'var(--z-toast)',
      top: 'var(--z-top)',
    },
    transitionDuration: {
      fast: 'var(--dur-fast)',
      base: 'var(--dur-base)',
      slow: 'var(--dur-slow)',
      slower: 'var(--dur-slower)',
    },
    transitionTimingFunction: {
      out: 'var(--ease-out)',
      'in-out': 'var(--ease-in-out)',
    },
    extend: {
      spacing: {
        '3xs': 'var(--space-3xs)',
        '2xs': 'var(--space-2xs)',
        xs: 'var(--space-xs)',
        sm: 'var(--space-sm)',
        md: 'var(--space-md)',
        lg: 'var(--space-lg)',
        xl: 'var(--space-xl)',
        '2xl': 'var(--space-2xl)',
        '3xl': 'var(--space-3xl)',
        '4xl': 'var(--space-4xl)',
        gutter: 'var(--space-gutter)',
        rule: 'var(--size-rule)',
        // Component sizes
        sidebar: 'var(--size-sidebar)',
        'control-sm': 'var(--size-control-sm)',
        control: 'var(--size-control)',
        'control-lg': 'var(--size-control-lg)',
        'thumb-w': 'var(--size-thumb-w)',
        'thumb-h': 'var(--size-thumb-h)',
        'avatar-md': 'var(--size-avatar-md)',
        'avatar-lg': 'var(--size-avatar-lg)',
        'avatar-xl': 'var(--size-avatar-xl)',
        'rail-sm': 'var(--size-rail-sm)',
        rail: 'var(--size-rail)',
        'cast-sm': 'var(--size-cast-sm)',
        cast: 'var(--size-cast)',
        'shot-sm': 'var(--size-shot-sm)',
        'shot-md': 'var(--size-shot-md)',
        shot: 'var(--size-shot)',
        'poster-sm': 'var(--size-poster-sm)',
        'poster-md': 'var(--size-poster-md)',
        poster: 'var(--size-poster)',
        'profile-sm': 'var(--size-profile-sm)',
        profile: 'var(--size-profile)',
        hero: 'var(--size-hero)',
        backdrop: 'var(--size-backdrop)',
        'backdrop-offset': 'var(--size-backdrop-offset)',
        dropdown: 'var(--size-dropdown)',
        'dropdown-h': 'var(--size-dropdown-h)',
        'panel-min': 'var(--size-panel-min)',
        'modal-h': 'var(--size-modal-h)',
        'sheet-h': 'var(--size-sheet-h)',
        'settings-nav': 'var(--size-settings-nav)',
        'field-sm': 'var(--size-field-sm)',
        'dock-clearance': 'var(--size-dock-clearance)',
        'empty-h': 'var(--size-empty-h)',
        spinner: 'var(--size-spinner)',
        logo: 'var(--size-logo)',
        'logo-sidebar': 'var(--size-logo-sidebar)',
      },
      maxWidth: {
        page: 'var(--width-page)',
        prose: 'var(--width-prose)',
        form: 'var(--width-form)',
        modal: 'var(--width-modal)',
        search: 'var(--width-search)',
        panel: 'var(--width-panel)',
        lightbox: 'var(--width-lightbox)',
      },
      borderWidth: {
        rule: 'var(--size-rule)',
      },
      maxHeight: {
        lightbox: 'var(--height-lightbox)',
      },
      scale: {
        hover: 'var(--scale-hover)',
        out: 'var(--scale-out)',
      },
      aspectRatio: {
        poster: '2 / 3',
        still: '16 / 9',
      },
      keyframes: {
        rise: {
          from: { opacity: '0', transform: 'translateY(var(--rise-distance))' },
          to: { opacity: '1', transform: 'none' },
        },
        fade: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        shimmer: {
          from: { backgroundPosition: '100% 0' },
          to: { backgroundPosition: '-100% 0' },
        },
        progress: {
          from: { transform: 'scaleX(0)' },
          to: { transform: 'scaleX(1)' },
        },
      },
      animation: {
        // `backwards` fill so the finished animation never pins opacity/transform
        // (cards rely on transitions for their fade-out after feedback).
        rise: 'rise var(--dur-slow) var(--ease-out) backwards',
        fade: 'fade var(--dur-base) var(--ease-out) backwards',
        shimmer: 'shimmer var(--dur-shimmer) linear infinite',
        // Hero carousel slide timer — its animationend advances the slide.
        progress: 'progress var(--dur-carousel) linear forwards',
      },
    },
  },
  plugins: [],
}
